#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.103.14.150:3306/passcs_chms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: guest
#    password: 123456
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: passcs-channel
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#server:
#  port: 8000