#spring:
#  datasource:
#    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.103.14.150:3306/passcs_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: guest
#    password: 123456
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: passcs-study
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#server:
#  port: 12000
